CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50) NOT NULL,
    priority    VARCHAR(10) NOT NULL,
    description VARCHAR(500),
    done        BOOLEAN     NOT NULL DEFAULT FALSE
);